version: "3.9"

services:

  postgres:
    image: "public.ecr.aws/docker/library/postgres:14.5-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5559:5432"

